### ISSUE TITLE
I cannot install applicationinsights-native-metrics@0.0.6

### ISSUE THREAD

**Issue by andreicristianpetcu** [microsoft/ApplicationInsights-node.js-native-metrics#16]
Hi all,

I ran `npm install applicationinsights-native-metrics@0.0.6` and got this error:

```
npm install applicationinsights-native-metrics@0.0.6

> applicationinsights-native-metrics@0.0.6 install C:\Users\joe\AppData\Roaming\npm\node_modules\applicationinsights-native-metrics
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Microsoft/ApplicationInsights-node.js-native-metrics/releases/download/v0.0.6/native_metrics-v0.0.6-node-v72-win32-x64-unknown.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for applicationinsights-native-metrics@0.0.6 and node@12.18.2 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Microsoft/ApplicationInsights-node.js-native-metrics/releases/download/v0.0.6/native_metrics-v0.0.6-node-v72-win32-x64-unknown.tar.gz
gyp ERR! find VS
gyp ERR! find VS msvs_version was set from command line or npm config
gyp ERR! find VS - looking for Visual Studio version 2012
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS checking VS2019 (16.3.29424.173) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional"
gyp ERR! find VS - "Visual Studio C++ core features" missing
gyp ERR! find VS checking VS2019 (16.9.31129.286) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - found VC++ toolset: v142
gyp ERR! find VS - missing any Windows SDK
gyp ERR! find VS checking VS2017 (15.9.28307.423) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - found VC++ toolset: v141
gyp ERR! find VS - missing any Windows SDK
gyp ERR! find VS checking VS2017 (15.9.28307.423) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - missing any VC++ toolset
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS valid versions for msvs_version:
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:310:5)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\joe\\AppData\\Roaming\\npm\\node_modules\\applicationinsights-native-metrics\\build\\Release\\native_metrics.node" "--module_name=native_metrics" "--module_path=C:\\Users\\joe\\AppData\\Roaming\\npm\\node_modules\\applicationinsights-native-metrics\\build\\Release" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72" "--msvs_version=2012"
gyp ERR! cwd C:\Users\joe\AppData\Roaming\npm\node_modules\applicationinsights-native-metrics
gyp ERR! node -v v12.18.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\joe\AppData\Roaming\npm\node_modules\applicationinsights-native-metrics\build\Release\native_metrics.node --module_name=native_metrics --module_path=C:\Users\joe\AppData\Roaming\npm\node_modules\applicationinsights-native-metrics\build\Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72 --msvs_version=2012' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\joe\AppData\Roaming\npm\node_modules\applicationinsights-native-metrics\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Windows_NT 10.0.18363
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\joe\\AppData\\Roaming\\npm\\node_modules\\applicationinsights-native-metrics\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\joe\AppData\Roaming\npm\node_modules\applicationinsights-native-metrics
node-pre-gyp ERR! node -v v12.18.2
node-pre-gyp ERR! node-pre-gyp -v v1.0.3
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\joe\AppData\Roaming\npm\node_modules\applicationinsights-native-metrics\build\Release\native_metrics.node --module_name=native_metrics --module_path=C:\Users\joe\AppData\Roaming\npm\node_modules\applicationinsights-native-metrics\build\Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72 --msvs_version=2012' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! applicationinsights-native-metrics@0.0.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the applicationinsights-native-metrics@0.0.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\joe\AppData\Roaming\npm-cache\_logs\2021-04-06T11_19_56_706Z-debug.lo
```

I have the latest VIsual Studio Community installed.
What am I doing wrong? How to fix?

**Comment by teberl** [comment]
### Problem
Same issue as described from @andreicristianpetcu. 
Trying to install the package under 
`System Linux 5.4.72-microsoft-standard-WSL2`
image `ubuntu`
`node v15.13.0`

```
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.1
npm ERR! node-pre-gyp info using node@15.13.0 | linux | x64
npm ERR! node-pre-gyp info check checked for "{pathToMyProject}/node_modules/applicationinsights-native-metrics/build/Release/native_metrics.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/Microsoft/ApplicationInsights-node.js-native-metrics/releases/download/v0.0.6/native_metrics-v0.0.6-node-v88-linux-x64-glibc.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Microsoft/ApplicationInsights-node.js-native-metrics/releases/download/v0.0.6/native_metrics-v0.0.6-node-v88-linux-x64-glibc.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for applicationinsights-native-metrics@0.0.6 and node@15.13.0 (node-v88 ABI, glibc) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Microsoft/ApplicationInsights-node.js-native-metrics/releases/download/v0.0.6/native_metrics-v0.0.6-node-v88-linux-x64-glibc.tar.gz
```

-----
### Update / Solution (for my machine)
After using the latest lts version of `node v14.16.1`, the installation was successful.

Maybe this could help you to @andreicristianpetcu ?

Good Luck 🍀🍀🍀

**Comment by hectorhdzg** [comment]
Fixed by #17, binaries for Windows must be available now

**Comment by Mathieu-DA** [comment]
I am having the same issue. My node version is 16.10
Please advise

**Comment by hectorhdzg** [comment]
@Mathieu-DA related to #22, we will publish with support for node 16 in January.

**Comment by Mathieu-DA** [comment]
@hectorhdzg 
Thanks for your response. In the meantime I just went ahead and followed the instructions provided https://github.com/nodejs/node-gyp#on-windows (link provided in npm i error log), namely installing python 3.9 and Visual Studio Build Tools. 
It solved the problem, but would have been nice to be spared the trouble :)
