### ISSUE TITLE
add release links for node 16

### ISSUE THREAD

**Issue by IKondor** [microsoft/ApplicationInsights-node.js-native-metrics#22]
Trying to install native metrics via npm

full log:
```
> npm i applicationinsights-native-metrics
npm ERR! code 1
npm ERR! path /path-to-my-repo/ssr_lazy_loading/node_modules/applicationinsights-native-metrics
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! Failed to execute '/home/oleg/.local/share/nvm/v16.2.0/bin/node /home/oleg/.local/share/nvm/v16.2.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/path-to-my-repo/ssr_lazy_loading/node_modules/applicationinsights-native-metrics/build/Release/native_metrics.node --module_name=native_metrics --module_path=/path-to-my-repo/ssr_lazy_loading/node_modules/applicationinsights-native-metrics/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.5
npm ERR! node-pre-gyp info using node@16.2.0 | linux | x64
npm ERR! node-pre-gyp info check checked for "/path-to-my-repo/ssr_lazy_loading/node_modules/applicationinsights-native-metrics/build/Release/native_metrics.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/Microsoft/ApplicationInsights-node.js-native-metrics/releases/download/v0.0.6/native_metrics-v0.0.6-node-v93-linux-x64-glibc.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Microsoft/ApplicationInsights-node.js-native-metrics/releases/download/v0.0.6/native_metrics-v0.0.6-node-v93-linux-x64-glibc.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for applicationinsights-native-metrics@0.0.6 and node@16.2.0 (node-v93 ABI, glibc) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Microsoft/ApplicationInsights-node.js-native-metrics/releases/download/v0.0.6/native_metrics-v0.0.6-node-v93-linux-x64-glibc.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.2.0 | linux | x64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.2.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.9.4 found at "/usr/bin/python3"
npm ERR! (node:39012) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/oleg/.local/share/nvm/v16.2.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/path-to-my-repo/ssr_lazy_loading/node_modules/applicationinsights-native-metrics/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/oleg/.local/share/nvm/v16.2.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/oleg/.cache/node-gyp/16.2.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/oleg/.cache/node-gyp/16.2.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/oleg/.local/share/nvm/v16.2.0/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/oleg/.cache/node-gyp/16.2.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/path-to-my-repo/ssr_lazy_loading/node_modules/applicationinsights-native-metrics',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.2.0 | linux | x64
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: not found: make
npm ERR! gyp ERR! stack     at getNotFoundError (/home/oleg/.local/share/nvm/v16.2.0/lib/node_modules/npm/node_modules/which/which.js:10:17)
npm ERR! gyp ERR! stack     at /home/oleg/.local/share/nvm/v16.2.0/lib/node_modules/npm/node_modules/which/which.js:57:18
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at step (/home/oleg/.local/share/nvm/v16.2.0/lib/node_modules/npm/node_modules/which/which.js:54:21)
npm ERR! gyp ERR! stack     at /home/oleg/.local/share/nvm/v16.2.0/lib/node_modules/npm/node_modules/which/which.js:71:22
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at subStep (/home/oleg/.local/share/nvm/v16.2.0/lib/node_modules/npm/node_modules/which/which.js:69:33)
npm ERR! gyp ERR! stack     at /home/oleg/.local/share/nvm/v16.2.0/lib/node_modules/npm/node_modules/which/which.js:80:22
npm ERR! gyp ERR! stack     at /home/oleg/.local/share/nvm/v16.2.0/lib/node_modules/npm/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /home/oleg/.local/share/nvm/v16.2.0/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! System Linux 5.11.0-17-generic
npm ERR! gyp ERR! command "/home/oleg/.local/share/nvm/v16.2.0/bin/node" "/home/oleg/.local/share/nvm/v16.2.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/path-to-my-repo/ssr_lazy_loading/node_modules/applicationinsights-native-metrics/build/Release/native_metrics.node" "--module_name=native_metrics" "--module_path=/path-to-my-repo/ssr_lazy_loading/node_modules/applicationinsights-native-metrics/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
npm ERR! gyp ERR! cwd /path-to-my-repo/ssr_lazy_loading/node_modules/applicationinsights-native-metrics
npm ERR! gyp ERR! node -v v16.2.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/home/oleg/.local/share/nvm/v16.2.0/bin/node /home/oleg/.local/share/nvm/v16.2.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/path-to-my-repo/ssr_lazy_loading/node_modules/applicationinsights-native-metrics/build/Release/native_metrics.node --module_name=native_metrics --module_path=/path-to-my-repo/ssr_lazy_loading/node_modules/applicationinsights-native-metrics/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/path-to-my-repo/ssr_lazy_loading/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! node-pre-gyp ERR! System Linux 5.11.0-17-generic
npm ERR! node-pre-gyp ERR! command "/home/oleg/.local/share/nvm/v16.2.0/bin/node" "/path-to-my-repo/ssr_lazy_loading/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /path-to-my-repo/ssr_lazy_loading/node_modules/applicationinsights-native-metrics
npm ERR! node-pre-gyp ERR! node -v v16.2.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.5
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/oleg/.npm/_logs/2021-05-27T10_28_29_409Z-debug.log
```

look at this line: `npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Microsoft/ApplicationInsights-node.js-native-metrics/releases/download/v0.0.6/native_metrics-v0.0.6-node-v93-linux-x64-glibc.tar.gz `

in your 0.0.6 release you have packages with node module's version 57, 64, 72, 83, 88, but no 93

can you add it?

**Comment by nulltoken** [comment]
@hectorhdzg in https://github.com/microsoft/ApplicationInsights-node.js-native-metrics/issues/16#issuecomment-993806868 you mentioned that binaries for Node 16 would be published in January 2022.

Would there be any chance for them to be released soon?

**Comment by hectorhdzg** [comment]
Fixed in latest release
